image: node:lts-alpine

stages:
    - install
    - build
    - publish

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - node_modules/

install:
    stage: install
    script:
        - npm ci

build:
    stage: build
    dependencies:
        - install
    script:
        - npm run prod-build
    artifacts:
        paths:
            - lib

publish:
    stage: publish
    needs:
        - job: build
          artifacts: true
    dependencies:
        - build
    script:
        - npm config set -- '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        - npm publish --access public
